# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
name: Quality Checks
on:
  push:
    branches:
      - main
      - dev
  pull_request:
  merge_group:

jobs:
  lint:
    name: ⬣ Quality Tests
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Download deps
        working-directory: scraper
        run: npm i

      - name: 🔬 Quality
        working-directory: scraper
        run: npm run validate

      - name: 📥 Download deps
        working-directory: web-app
        run: npm i

      - name: 🔬 Quality
        working-directory: web-app
        run: npm run validate
