# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
name: Web App
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  # Auto deploy daily to get the latest legislation data
  schedule:
    - cron: "0 6 * * *" # Run daily at 6:00 UTC (1am Central)

jobs:
  lint:
    name: 🔬 Web App Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 NPM Install
        working-directory: web-app
        run: npm i

      - name: 🔬 Quality
        working-directory: web-app
        run: npm run quality

  build-web-app:
    # only deploy main branch on pushes
    # if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

    name: 🏗️ Build Web App & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 NPM Install
        env:
          # Required for .env creation
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        working-directory: web-app
        run: npm i

      - name: 🏗️ Build
        working-directory: web-app
        run: npm run build

      # Publish built files to GitHub Pages repo
      - name: Deploy to GitHub Pages Repo
        id: deployment
        env:
          # Define variables for clarity and flexibility
          GH_USERNAME: windy-civi # Typically 'main' for GitHub Pages root repo
          DIST_REPO: windy-civi/dist # Typically 'main' for GitHub Pages root repo
          GH_PAGES_REPO: windy-civi.github.io # Replace with your GitHub Pages repo name
          GH_PAGES_BRANCH: main # Typically 'main' for GitHub Pages root repo
        run: |
          echo "Clone the GitHub Pages repository"
          git clone https://<token>@github.com/$GH_USERNAME/$GH_PAGES_REPO.git ../$GH_PAGES_REPO
          cd ../$GH_PAGES_REPO

          echo "Clear out old files"
          rm -rf *

          echo "Copy the new build files from the source repository"
          cp -r ../$DIST_REPO/* .

          echo "Commit and push changes"
          git config --unset-all http.https://github.com/.extraheader
          git add .
          git commit -m "Deploy from source repo"
          git push origin $GH_PAGES_BRANCH
